In [2]:
import numpy as np
# exam
# 넘파이 배열을 사용하여 1부터 20까지의 연속된 정수값을 가지는 1차원 배열을 생성하여
# 실행결과와 같이 출력되기 위해 알맞은 코드를 쓰시오.


# 마지막 원소 : 20
# 모든 원소의 합 : 210
# 모든 원소의 평균 : 10.5
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]]
num_arr1 = np.arange(1, 21)
print(num_arr1)

print(f'마지막 원소 : {num_arr1[num_arr1.size - 1]}')
print(f'마지막 원소 : {num_arr1[-1]}')
print(f'모든 원소의 합 : {num_arr1.sum()}')
print(f'모든 원소의 평균 : {num_arr1.mean()}')
print(num_arr1.reshape(4, 5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
마지막 원소 : 20
마지막 원소 : 20
모든 원소의 합 : 210
모든 원소의 평균 : 10.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [3]:
# 학생들의 근로 장학금이 넘파이 배열에 저장되어 있다.
# 이번 학기 학생들의 근로장학금을 1.5배 올려주려고 한다.
# 다음은 인상된 근로장학금을 출력하고 근로장학금이 평균 근로장학금보다 많은 학생들의 근로장학금을 출력하고
# 원소의 수를 출력하는 프로그램이다.

import numpy as np

salary = [200, 150, 180, 220, 250]

# 인상된 금액 : [300. 225. 270. 330. 375.]
# 평균 금액 : 300.0
# 평균이상인 원소 : [300. 330. 375.]
# 평균이상인 원소의 개수 : 3

salary = np.array(salary) * 1.5
print(f'인상된 금액 : {salary}')
print(f'평균 금액 : {salary.mean()}')
print(f'평균 이상인 원소 : {salary[salary >= salary.mean()]}')
print(f'평균이상인 원소의 개수 : {(salary[salary >= salary.mean()]).size}')

인상된 금액 : [300. 225. 270. 330. 375.]
평균 금액 : 300.0
평균 이상인 원소 : [300. 330. 375.]
평균이상인 원소의 개수 : 3
