In [3]:
# 3. 배열의 인덱싱과 슬라이싱
import numpy as np

# 인덱싱 Indexing : 배열의 위치나 조건을 지정해 배열의 원소를 선택
# 슬라이싱 Slicing : 범위를 지정해 배열의 원소를 선택.

# 1) 배열의 인덱싱.
# 1차원 배열에서 특정 위치의 원소를 선택하려면 원소의 위치를 지정.
# 배열명[위치]
# 배열 원소의 위치는 0부터 시작.

a1 = np.array([0, 10, 20, 30, 40, 50])

print(a1[0])    # 0
print(a1[4])    # 40

# 배열을 변경
a1[5] = 70
print(a1)  # [ 0 10 20 30 40 70]

# 1차원 배열에서 여러 개의 원소를 선택.
# 배열명[ 위치1, 위치2, ... , 위치n]

print(a1[[1, 3, 4]])  # [10 30 40]

# 2차원 배열에서 특정 위치의 원소를 선택하려면 행과 열의 위치를 지정.
# 배열명[행_위치, 열_위치]
print()
# 10부터 99까지 10씩 증가하는 1차원 배열을 생성한 후에 3행 3열의 2차원 배열로 모양을 바꿈.
a2 = np.arange(10, 100, 10).reshape(3, 3)
# np.arange(10, 100, 10) 으로 1차원 배열을 생성하고  reshape(3, 3) 으로 2차원 배열로 만들어라 3행 3열로 변경하라

print(a2)
# [[10 20 30]
#  [40 50 60]
#  [70 80 90]]

# -->[[10 20 30] [40 50 60] [70 80 90] ]
# exam
# 행위치가 0이고, 열 위치가 2인 원소를 반환하라.
print(a2[0, 2])  # 30 <-- Numpy에서 주로 쓰는 방법
print(a2[0][2])  # 30 <-- 기존의 방식으로도 가능하다

# 2차원 배열의 행과 열의 위치를 지정해서 원소를 선택한 후 값을 변경할 수 잇음.
a2[2, 2] = 95
print(a2)
# [[10 20 30]
#  [40 50 60]
#  [70 80 95]]
print()

# 2차원 배열의 여러 원소를 선택하기 위해서 아래와 같이 지정.
# 배열명[[행_위치1, 행_위치2, ... , 행_위치n], [열_위치1, 열_위치2, ... , 열_위치n]]

print(a2[[0, 2], [0, 1]])  # [10 80]



0
40
[ 0 10 20 30 40 70]
[10 30 40]

[[10 20 30]
 [40 50 60]
 [70 80 90]]
30
30
[[10 20 30]
 [40 50 60]
 [70 80 95]]

[10 80]


In [4]:
import numpy as np

# 배열에 조건을 지정해 조건을 만족하는 배열을 선택(조건에 맞는 배열만 출력이 가능하다)
# 배열명[whrjs]

a = np.array([1, 2, 3, 4, 5, 6])
print(a[a > 3])  # [4 5 6]

# 짝수만 선택하는 예.
print(a[a % 2 == 0])  # [2 4 6]
# 통상적으로 반복문을 돌려야 했는데 numpy를 사용하면 그렇게 안해도 된다.
a1 = np.array([0, 10, 20, 30, 40, 50])

# -인덱스도 사용가능
print(a1[-2])  # 40

[4 5 6]
[2 4 6]
40


In [ ]:
import numpy as np

# 2) 배열의 슬라이싱.
# 1차원 배열의 경우 슬라이싱은 배열의 시작과 끝 위치를 지정.
# 배열[시작_위치:끝_위치]
# 반환되는 원소의 범위는 '시작_위치 ~ 끝_위치 - 1'
# 시작 위치를 지정하지 않으면 0.
# 끝 위치를 지정하지 않으면 배열이 길이.

b1 = np.array([0, 10, 20, 30, 40, 50])
print(b1[1:4])  # [10 20 30]. 1 ~ 3

# 1차원 배열에서 '시작_위치'와 '끝_위치'를 지정하지 않고 슬라이싱 하는 예.
print(b1[:3])  #   [ 0 10 20]. 0 ~ 2

print(b1[2:])  # [20 30 40 50]. 2~

print(b1[:])  # [ 0 10 20 30 40 50]

# 슬라이싱을 이용해 원소를 변경할 수 있음.
b1[2:5] = np.array([25, 35, 45])
print(b1)  # [ 0 10 25 35 45 50]   # 2 ~ 4 변경

# 여러 원소의 값을 같은 값으로 변경하는 예.
b1[3:6] = 60
print(b1)  # [ 0 10 25 60 60 60] # 3 ~ 5 변경
