In [3]:
import numpy as np

# 배열에 조건을 지정해 조건을 만족하는 배열을 선택(조건에 맞는 배열만 출력이 가능하다)
# 배열명[whrjs]

a = np.array([1, 2, 3, 4, 5, 6])
print(a[a > 3])  # [4 5 6]

# 짝수만 선택하는 예.
print(a[a % 2 == 0])  # [2 4 6]
# 통상적으로 반복문을 돌려야 했는데 numpy를 사용하면 그렇게 안해도 된다.
a1 = np.array([0, 10, 20, 30, 40, 50])

# -인덱스도 사용가능
print(a1[-2])  # 40

[4 5 6]
[2 4 6]
40


In [10]:
import numpy as np

# 2) 배열의 슬라이싱.
# 1차원 배열의 경우 슬라이싱은 배열의 시작과 끝 위치를 지정.
# 배열[시작_위치:끝_위치]
# 반환되는 원소의 범위는 '시작_위치 ~ 끝_위치 - 1'
# 시작 위치를 지정하지 않으면 0.
# 끝 위치를 지정하지 않으면 배열이 길이.

b1 = np.array([0, 10, 20, 30, 40, 50])
print(b1[1:4])  # [10 20 30]. 1 ~ 3

# 1차원 배열에서 '시작_위치'와 '끝_위치'를 지정하지 않고 슬라이싱 하는 예.
print(b1[:3])  #   [ 0 10 20]. 0 ~ 2

print(b1[2:])  # [20 30 40 50]. 2~

print(b1[:])  # [ 0 10 20 30 40 50]

# 슬라이싱을 이용해 원소를 변경할 수 있음.
b1[2:5] = np.array([25, 35, 45])
print(b1)  # [ 0 10 25 35 45 50]   # 2 ~ 4 변경

# 여러 원소의 값을 같은 값으로 변경하는 예.
b1[3:6] = 60
print(b1)  # [ 0 10 25 60 60 60] # 3 ~ 5 변경


[10 20 30]
[ 0 10 20]
[20 30 40 50]
[ 0 10 20 30 40 50]
[ 0 10 25 35 45 50]
[ 0 10 25 60 60 60]


In [45]:
# exam
# 넘파이 배열을 사용하여 1부터 20까지의 연속된 정수값을 가지는 1차원 배열을 생성하여
# 실행결과와 같이 출력되기 위해 알맞은 코드를 쓰시오.


# 마지막 원소 : 20
# 모든 원소의 합 : 210
# 모든 원소의 평균 : 10.5
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]]
num_arr1 = np.arange(1, 21)
print(num_arr1)

print(f'마지막 원소 : {num_arr1[num_arr1.size - 1]}')
print(f'마지막 원소 : {num_arr1[-1]}')
print(f'모든 원소의 합 : {num_arr1.sum()}')
print(f'모든 원소의 평균 : {num_arr1.mean()}')
print(num_arr1.reshape(4, 5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
마지막 원소 : 20
마지막 원소 : 20
모든 원소의 합 : 210
모든 원소의 평균 : 10.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [78]:
# 학생들의 근로 장학금이 넘파이 배열에 저장되어 있다.
# 이번 학기 학생들의 근로장학금을 1.5배 올려주려고 한다.
# 다음은 인상된 근로장학금을 출력하고 근로장학금이 평균 근로장학금보다 많은 학생들의 근로장학금을 출력하고
# 원소의 수를 출력하는 프로그램이다.

import numpy as np

salary = [200, 150, 180, 220, 250]

# 인상된 금액 : [300. 225. 270. 330. 375.]
# 평균 금액 : 300.0
# 평균이상인 원소 : [300. 330. 375.]
# 평균이상인 원소의 개수 : 3

salary = np.array(salary) * 1.5
print(f'인상된 금액 : {salary}')
print(f'평균 금액 : {salary.mean()}')
print(f'평균 이상인 원소 : {salary[salary >= salary.mean()]}')
print(f'평균이상인 원소의 개수 : {(salary[salary >= salary.mean()]).size}')

인상된 금액 : [300. 225. 270. 330. 375.]
평균 금액 : 300.0
평균 이상인 원소 : [300. 330. 375.]
평균이상인 원소의 개수 : 3
